### ISSUE TITLE
a6000 focus magnification

### ISSUE THREAD

**Issue by schmety** [KillerInk/BetterManual#2]
Hi there !
First, thanks for this application, it's one of my favorite and makes my life easier :)
I have already installed Better Manual on my Sony a5000 and a5100 camera.
I mainly and mostly use manual mode , for landscapes, macro, nightphotos.
I didn't know that there is also this version of Better Manual for a6000, cause i was missing
focus magnification option in version which i have for a5000 and a5100 model.
So, this is awesome to have now focus magnification also at a6000 model !
I just have one question, is there maximum magnification 5.90x and not 11.70x ?
Thanks and best regards, 
Matej

**Comment by KillerInk** [comment]
update is pushed. note the navigation got changed. check the readme

**Comment by schmety** [comment]
I have installed latest version, but i have some problems now.
Application won't start and every time i want to press Better Manual, camera goes back into main camera screen. also if i try few time to start Better Manual back, camera freezes. 
So, i must to remove battery and then start again.
I have installed 1.5.2 version back and it works.
Best

**Comment by KillerInk** [comment]
pls try this. tested the apk on my a6000
https://github.com/KillerInk/BetterManual/releases/download/1.5.5_A6000/BetterManual-debug_1.5.5.apk

**Comment by schmety** [comment]
thanks, i will test your new apk version tomorrow evening and report back.

**Comment by schmety** [comment]
I have installed latest version of apk. 
First try it was ok, like it works normal. I have tried all settings and shoot bracketing option.
It was fine.
Then after going back to camera's menu and tried back to Better Manual, then camera won't start Better Manual. It goes back to camera's Manual mode.
After few tries, camera's lcd screen goes black again.

**Comment by KillerInk** [comment]
this is now relativ stable.
https://github.com/KillerInk/BetterManual/releases/tag/1.5.6_A6000

**Comment by schmety** [comment]
i really don't know, does this also depends from camera to camera model, but,
i have installed new version, while going into Better Manual screen stays black or goes back to camera's default or freezes.
Back to version 1.5.2, which works.
video link : https://filebin.net/zpijyzgpfdxynn65

**Comment by KillerInk** [comment]
i also dont know, its a bit strange. here its working without problems.
how are you installing the apk? through pmca gui/console or due adb?
you have manual lens mounted?
pls check your sd card if it cointains a BMANUAL.txt. there the uncaughtexeptions get stored

**Comment by schmety** [comment]
i'm installing thru pmca gui/console.
i had manual lens mounted, kit lens or no lens, it was the same. 1.5.2 version worked with any of those combination.
i have BMANUAL.txt on my SD card. 
link : https://easyupload.io/128ewd (link to .txt file)

**Comment by schmety** [comment]
I was thinking, on which firmware camera version are you working with ? I have the latest, 3.21 installed.

**Comment by KillerInk** [comment]
Im too on 3.2.1, from the log it looks like your sd card is empty. Pls make sure you have one img stored on it. Without img mine acts like yours. It start and crash wich cause a black screen/reboot the camera

**Comment by schmety** [comment]
I see.
I will try that and report back.

**Comment by schmety** [comment]
Ok, i have tested now again version 1.5.6.
Like you said, it works now. Here and there, application goes to (restarts) cameras menu, like already few times before.
I shoot a lot at night and i have question, there is option Long exposure NR, should i leave it OFF or ON ?
Also how can i escape from option, when i enter "Landscape icon" and is this for macro shooting ?

**Comment by KillerInk** [comment]
long exposure noise reduction close the shutter after a capture for the same time.
if you take startrails you get  gaps in the trails. if you do deep sky stuff it may be usefull to filter out some noise.

that landscape icon is a simple af bracket. press the enter key till the counter runs. and once more to stop it. i forgot there to change the naming and navigation

**Comment by schmety** [comment]
Thanks for explanation !
I shoot mostly milkyway, deep space too.
So , for that purpose is better to leave this ON  ?
Probably i'll purchase another a6000 . but full spectrum, i have already a5000 full spectrum.
How much % better you think should a6000 be ? At least 10% or something similar ?

**Comment by KillerInk** [comment]
its mostly up to the conditions you shot and how long your exposure is and how many shoots want to take. with longer exposure and many images the sensor heat increase wich leads to more electrical noise.
you can see the long exposure noise reduction like a darkframe. 
it contains only the noise and get in the postprocessing substracted from the orginal frame.
normaly you capture the sky and after that you mount the lenshood and capture the same exposure again.
you can skip that step with the longExNR. 

i dont think that the difference is big between a6000/5000. a6000 sensor is a bit bigger and get due that more light. but if its realy 10%, no idea.

**Comment by schmety** [comment]
Thanks for all info and explanation.
